spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:8b #must allow tools; list could be found @ https://ollama.com/library 
          keep-alive: 30m 
          temperature: 0.2 
    mcp:
      client:
        enabled: true
        type: SYNC
        request-timeout: 45s
        toolcallback:
          enabled: true     
        stdio:
          root-change-notification: false
          connections:
            elasticsearch:
              #path where the elasticsearch mcp server exist & this command runs it 
              command: /home/arivera/mcp-server-elasticsearch/target/release/elasticsearch-core-mcp-server
              args: ["stdio"]
              env:
                ES_URL: "http://localhost:9201"
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG


